# permissions for end users to view elasticworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticworker-viewer-role
rules:
- apiGroups:
  - elasticcluster.sarweshsuman.com
  resources:
  - elasticworkers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticcluster.sarweshsuman.com
  resources:
  - elasticworkers/status
  verbs:
  - get
