# permissions for end users to view elasticworkerautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticworkerautoscaler-viewer-role
rules:
- apiGroups:
  - elasticcluster.sarweshsuman.com
  resources:
  - elasticworkerautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticcluster.sarweshsuman.com
  resources:
  - elasticworkerautoscalers/status
  verbs:
  - get
