apiVersion: elasticcluster.sarweshsuman.com/v1
kind: ElasticWorker
metadata:
  name: elasticworker-sample
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleInPolicy:
    name: selector
    selector:
      matchLabels:
        delete: "true"
  selector:
    matchLabels:
      worker: elastic-workers
  template:
    metadata:
      labels:
        worker: elastic-workers
    spec:
      containers:
      - name: worker-1
        image: busybox:latest
        command: ['sleep','30000']
